version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tasks_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tasks_db
      MYSQL_USER: tasks_user
      MYSQL_PASSWORD: tasks_password
    ports:
      - "3306:3306"
    volumes:
      - tasks_mysql_data:/var/lib/mysql
    networks:
      - tasks_network

networks:
  tasks_network:

volumes:
  tasks_mysql_data: